version: '3.7'
services:
  app:
    build:
      context: .
      target: dev
    restart: unless-stopped
    ports:
      - 3500:3500
    volumes:
      - ./videos:/usr/src/app/videos
      - ./src:/usr/src/app/src
      - ./data:/usr/src/app/data
